### ISSUE TITLE
install issue, am I doing something wrong?

### ISSUE THREAD

**Issue by tedx** [mapbox/node-mbtiles#78]
[tedx@ ~]$ sudo npm install @mapbox/mbtiles
npm ERR! git clone git@github.com:mapbox/mbtiles Initialized empty Git repository in /root/.npm/_git-remotes/git-github-com-mapbox-mbtiles-44905b0c/
npm ERR! git clone git@github.com:mapbox/mbtiles 
npm ERR! git clone git@github.com:mapbox/mbtiles FIPS integrity verification test failed.
npm ERR! git clone git@github.com:mapbox/mbtiles Permission denied (publickey).
npm ERR! git clone git@github.com:mapbox/mbtiles fatal: The remote end hung up unexpectedly
npm ERR! addLocal Could not install mapbox/mbtiles
npm ERR! Error: ENOENT, stat 'mapbox/mbtiles'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "@mapbox/mbtiles"
npm ERR! cwd /home/tedx
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR! path mapbox/mbtiles
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tedx/npm-debug.log
npm ERR! not ok code 0

**Comment by mapsam** [comment]
Hi @tedx - 

> node -v v0.10.48
> npm -v 1.3.6

It looks like you are using some very old versions of Node and NPM - both of which are no longer developed. Since the module is now scoped under the Mapbox organization on NPM (i.e. `@mapbox/mbtiles`) you'll need a version of NPM that supports this. I recommend installing with at least node v4 and npm3 - but would aim for node v6+ and NPM v5+.

> git clone git@github.com:mapbox/mbtiles

It also looks like it's trying to clone from an older version of this repository, so yeah... updating NPM and node should get you moving forward. Please re-open if this doesn't help!
